### ISSUE TITLE
Session 1: Topics

### ISSUE THREAD

**Issue by HillmerCh** [neomatrix369/java-10-and-beyond#2]
@neomatrix369 @rahmanusta. WDYT about to make the Session 1 for Local-Variable Type Inference, with some of next workshop:

1.  Where can not be used Local-Variable Type Inference
2. Where can be used Local-Variable Type Inference
3. Local-Variable Type Inference on JShell, in this WorkShop we can use both the JShell that JDK brings and the Shell web version created by Rahman https://tryjshell.org

**Comment by neomatrix369** [comment]
Let me come back with examples of this

+1 for point 3. (in addition to also showing it via compilable source file)

**Comment by neomatrix369** [comment]
WIP: #1, #3 and commits thereafter are fulfilling this issue partially

**Comment by HillmerCh** [comment]
WIP
